---

 
- name: IOS Verification 
  hosts: routers
 
  vars:
    upgrade_ios_version: 15.2(55)SE12
 
  tasks:
    - name: CHECK CURRENT VERSION
      ios_facts:
 
    - debug:
        msg:
        - "Current version is {{ ansible_net_version }}"
        - "Upgrade image is 15.2(55)SE12"
 
    - debug:
        msg:
        - "Image is not compliant and will be upgraded"
 
      when: ansible_net_version != upgrade_ios_version
